# -*- coding: utf-8 -*-
"""Key-Value_Nadia_MBD_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KwUwkbYqqRTHor2hZMCqoqsW1aYtltZn
"""

# Simulasi key-value menggunakan dictionary Python
db = {
    "user:1": "Nadia",
    "user:2": "Rizki",
    "user:3": "Andi",
    "user:4": "Siti",
    "user:5": "Bayu"
}

# Akses data
print(db["user:1"])