# -*- coding: utf-8 -*-
"""Wide-Column_Nadia_MBD_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KwUwkbYqqRTHor2hZMCqoqsW1aYtltZn
"""

siswa = {
    1: {"name": "Nadia", "math": 90, "science": 85, "english": 88},
    2: {"name": "Rizki", "math": 75, "science": 80},
    3: {"name": "Siti", "science": 90, "english": 95},
    4: {"name": "Andi", "math": 85, "english": 78},
    5: {"name": "Bayu", "math": 80, "science": 70, "english": 82},
}

# Akses data
print(siswa[1]["name"])
print(siswa[3]["english"])